function skillsMember() {
    var self = this;
    self.skills = ko.observableArray();
    self.skills.push(new skillItem("C#", 1));
    self.skills.push(new skillItem("Java", 2));
    self.skills.push(new skillItem("JavaScript", 3));
    self.skills.push(new skillItem("SQL", 4));
    self.skills.push(new skillItem("HTML", 5));
    self.skills.push(new skillItem("CSS", 6));
    self.skills.push(new skillItem("C++", 7));
    self.skills.push(new skillItem("Python", 8));
    self.skills.push(new skillItem("PHP", 9));
    self.skills.push(new skillItem("Ruby", 10));
    self.skills.push(new skillItem("Perl", 11));
    self.skills.push(new skillItem("Swift", 12));
    self.skills.push(new skillItem("Objective-C", 13));
    self.skills.push(new skillItem("Kotlin", 14));
    self.skills.push(new skillItem("R", 15));
    self.skills.push(new skillItem("Scala", 16));
    self.skills.push(new skillItem("Go", 17));
    self.skills.push(new skillItem("Visual Basic", 18));
    self.skills.push(new skillItem("Matlab", 19));
    self.skills.push(new skillItem("Assembly", 20));
    self.skills.push(new skillItem("Rust", 21));
    self.skills.push(new skillItem("Dart", 22));
    self.skills.push(new skillItem("Groovy", 23));
    self.skills.push(new skillItem("Bash", 24));
    self.skills.push(new skillItem("Haskell", 25));
    self.skills.push(new skillItem("Lua", 26));
    self.skills.push(new skillItem("TypeScript", 27));
    self.skills.push(new skillItem("CoffeeScript", 28));
    self.skills.push(new skillItem("OCaml", 29));
    self.skills.push(new skillItem("Clojure", 30));
    self.skills.push(new skillItem("Elixir", 31));
    self.skills.push(new skillItem("Erlang", 32));
    self.skills.push(new skillItem("F#", 33));
    self.skills.push(new skillItem("Haxe", 34));
    self.skills.push(new skillItem("Julia", 35));
    self.skills.push(new skillItem("Kotlin",36));
}